### ISSUE TITLE
Mirro Shaz Shrine Crash

### ISSUE THREAD

**Issue by ImJustSofa** [CEObrainz/Second-Wind#1]
"The game crashes when attempting to enter Mirro Shaz Shrine (Dungeon056) using the latest CEMU build (1.26.0d). Have not tested on console yet. The game will either freeze or crash while the loading screen has filled in up to around the L on Zelda."

Steps to Reproduce:

1. Enter the Mirro Shaz Shrine and notice the game crashing during loading

Reported by Coral#0360

**Comment by CEObrainz** [comment]
Tested with SWv1.9.11a - Cemu 1.26.0d - BCML 3.7.2

Unable to reproduce issue.
