### ISSUE TITLE
bug in the output of abandoned mine

### ISSUE THREAD

**Issue by arthur4272** [CEObrainz/Second-Wind#10]
![bug](https://user-images.githubusercontent.com/99784398/154202803-6efb73e2-3456-4943-8228-cfa1cc4b305a.png
I have a problem that after defeating the hinox king I can't get out of the abandoned mine, nothing appears when trying to interact with the statue, does anyone know how to solve it?

**Comment by CEObrainz** [comment]
Fixed in Latest Nightly (2022/02/19), fix will be in v1.9.12
