### ISSUE TITLE
Knight of Ordon issue

### ISSUE THREAD

**Issue by h4rl0ck48** [CEObrainz/Second-Wind#12]
H4rl0ck71#1492
Cemu / Nightly 2-20-22

Issue: Playing yesterday on my oldest save file and did the rebuilt the ordon lab quest. No issues. 

Today I update to latest nightly and im currently using a save file that was missing the last part of Knight of Ordon, i am supposed to talk to Rakib after giving the tea to Risho. Well, I went to talk to Rakib and instead of tell me to help him to fight the enemy at the entrance of Ordon, he gave me the Hylian Knights quest instead of finishing Knight of Ordon or the Repair the lab quest. I did not get the errand quest either.

**Comment by h4rl0ck48** [comment]
Seems that the Hylian Knights quest is overwriting the other two. Not letting the other 2 quest to complete or proceed to next stage

**Comment by CEObrainz** [comment]
Fixed in Latest Nightly
