### ISSUE TITLE
Not all blue flame lamps are lit, Ordon Ancient Tech Lab still lit

### ISSUE THREAD

**Issue by WLuethi** [CEObrainz/Second-Wind#13]
TITLE: Brief Description of the issue: 
Not all blue flame lamps are lit, Ordon Ancient Tech Lab still lit

DiscordName#: 
ib4#1111

Platform: 
Wii U/Cemu

Mod Version: 
1.9.11b

Game Version: 
208(as listed in cemu game page column)

Detailed description of the issue:
When I first installed the mod, the first thing I did was light all the lamps and activate the new tech lab. Many weeks later I was riding around and realized one of the first 3 lamps wasn't lit.

Exact steps to reproduce the issue: NA

I will only host the video for one week then remove it, please download it to save for review. Also, please excuse the glitch where the ancient tech lab platform is missing. I imagine this happens because I am using FREECAM along side CEMU to zoom around.

Video of bug: https://vimeo.com/680022184

**Comment by CEObrainz** [comment]
I cannot view that video, do you mind first lighting the torches that weren't lit, save and reload. If it still isn't lit after reloading please make a note of the ones that do this.

From my perspective they all seem to be fine.

**Comment by WLuethi** [comment]
Here, I've taken a screenshot of the beginning where it shows the unlit torch, with a lit torch in the background, and then a second screen shot of the ancient lab lit up. I will try your troubleshoot as well
![ceobrain1](https://user-images.githubusercontent.com/9699562/155144859-35e5162e-325f-4e0c-8dca-e519306b61ed.png)
![ceobrain2](https://user-images.githubusercontent.com/9699562/155144871-a8156862-c210-40d0-9780-c82608de1861.png)
.

**Comment by CEObrainz** [comment]
Did my suggestion change anything?
