### ISSUE TITLE
2 chests in Myahm Agana Depths respawn their contents after reentering, and do not mark the shrine on the map with a chest icon when collected

### ISSUE THREAD

**Issue by M1CR0H4CK3R** [CEObrainz/Second-Wind#15]
TITLE: Brief Description of the issue:

DiscordName#: Maq47#3451

Platform: Cemu 1.26.2f

Mod Version: 1.9.11a

Game Version: v208

Detailed description of the issue:

In Myahm Agana Depths (Shrine in Hateno Village), only the first chest Link can encounter keeps its state. All others respawn their contents upon reentering. Also, it is impossible to get the chest icon on the map icon for the shrine, as collecting all 3 chests' contents does not award the icon.

Exact steps to reproduce the issue:

1.) In Myahm Agana Depths, open all 3 chests.
2.) Leave Myahm Agana Depths without collecting the Spirit Orb.
3.) Re-enter the shrine, and recheck the 2nd and third chests in the shrine.
4.) Chests #2 and #3 can be reopened.

![image](https://user-images.githubusercontent.com/1993598/155092148-a5950ad8-6fc8-4983-ab72-8c213424b550.png)

![image](https://user-images.githubusercontent.com/1993598/155092532-8f35a618-4e5e-4f7d-850c-124d4579b236.png)

(The game crashed while trying to take the 3rd screenshot; will edit later if requested)

(The game crashed before I could take a screenshot of the map screen; will edit later if requested)

**Comment by CEObrainz** [comment]
Flags will be added at a later date.
