### ISSUE TITLE
Recruit Questline Issues (so far)

### ISSUE THREAD

**Issue by DreadlordZolias** [CEObrainz/Second-Wind#16]
So far, I've only gotten to the Recruit: The Sword Maiden and Recruit: Master of Torches, in that order of acquisition.  The issues I've noticed are as follows:

At the end of the questline of The Sword Maiden, her text is all over the place and outside of the text box in places.

In Master of Torches, the quest log and destination marker is showing that of The Sword Maiden's - it's telling me to go to Ash Swamp and the marker is telling me to go to Zora's Domain despite being told to go to a small chain of islands off of the coast which I'm assuming are what I like to call the "Tingle Brother Isles".

There may be more, but this is as far as I've gotten.

**Comment by CEObrainz** [comment]
This is wip content that's unfinished, as such its not a bug.
