### ISSUE TITLE
Link missing after warping to certain areas in nightly builds

### ISSUE THREAD

**Issue by CryoByte33** [CEObrainz/Second-Wind#19]
TITLE: Link missing after warping to certain areas in nightly builds.

DiscordName#: Cryobyte33#0345

Platform: Cemu

Mod Version: Nightlies 2022-03-06 and 2022-03-07

Game Version: v208

Detailed description of the issue:
Warping to anywhere near Tabantha/Hebra results in Link not appearing post-warp.

![bug](https://user-images.githubusercontent.com/11524686/157107273-96091ff9-a2d2-4ee0-8baa-3e67045ae5b7.png)

* Warping to Rito Village, Tabantha tower or Hebra tower will make him invisible and unable to move. (I lack further warp points at this time)
* I can still get into the menu and warp other places after he has vanished. If I warp to a "good" point, he reappears and is playable again.
* His shadow IS visible.
* I can walk to any of the destinations with no issue

NOTE: My save file originally included HyRe and several other mods, but the issue persists after the other mods are disabled.

Exact steps to reproduce the issue:
1. Unlock warp point for one of the locations mentioned above.
2. Travel away from the general area, either by foot or warp.
3. Attempt to warp to one of the locations mentioned above

I'm also attaching a copy of my save games for BotW. Pardon the messy files, I didn't know exactly which contents you'd need to diagnose any issues.
[save.zip](https://github.com/CEObrainz/Second-Wind/files/8200420/save.zip)

**Comment by ShadowSlayerFX1** [comment]
i have sort of the same problem but after warping anyware link misses the second warp animation

**Comment by CEObrainz** [comment]
Requires updated version of BCML
