### ISSUE TITLE
Freezing during load. 

### ISSUE THREAD

**Issue by nfinitly** [CEObrainz/Second-Wind#2]
Ruya Nala Shrine freezes on the "L" in "Zelda" when loading.

Wii-u version on my PC. No other mods installed. Everything up-to-date.

16gb RAM. 1070 GTX. Ryzen 3700x.

**Comment by CEObrainz** [comment]
Do you have all DLC installed?

**Comment by CEObrainz** [comment]
Yes, that'll solve the issue for you. Please purchase and dump the DLCs, Cemu also has a way to directly download any DLC you own.
