### ISSUE TITLE
Monya Toma Shrine - Missing ball near entrance making puzzle incompletable

### ISSUE THREAD

**Issue by ItsCorbob** [CEObrainz/Second-Wind#21]
**DiscordName#**
Corbob#6995

**Platform**
Wii U/Cemu
Cemu Version: 1.26.2f

**Mod Version**
1.9.11b-nightly

**Game Version**
Breath of the Wild (USA)
Update - 208
DLC - 80

**Description**
Monya Toma Shrine at the entrance has a ball pedestal, however, there is no ball in it. Without it, the puzzle itself becomes incompletable.

**Reproduction Steps**
1. Enter the Monya Toma Shrine.
2. Observe the dimple in the ground that would hold the puzzle ball is missing the ball.

![image](https://user-images.githubusercontent.com/102060294/159330993-1083b73f-fe0e-462b-ac53-77ddd6cf2b09.png)

**Comment by ItsCorbob** [comment]
I was able to complete the shrine through another method, although I am almost positive that's not the intended method

**Comment by CEObrainz** [comment]
The ball was moved, this is intended.
