### ISSUE TITLE
often blood moon

### ISSUE THREAD

**Issue by fermel01** [CEObrainz/Second-Wind#22]
Hi, I think Second-Wind is an excellent job.
I have installed the latest version on my console table, and this mod runs excellent. , however I can't play it the way I wanted to, since every 3 minutes or so the blood moon comes out and it's annoying that the blood moon appears so frequently. I don't know if the game is like that or did I do something wrong?

Thanks for everything.
Best regards

**Comment by CEObrainz** [comment]
Duplicate of #24
