### ISSUE TITLE
Ordon Sword Missing Textures

### ISSUE THREAD

**Issue by LuckyMist8** [CEObrainz/Second-Wind#28]
LuckyMist8#8669

Platform: Cemu

Mod Version: 1.9.12

Game Version: Latest

The Ordon Sword That I Got From The Blacksmith In Ordon Village Has A Jumbled Looking Texture, Like It's Missing.
The Model Looks Fine, But The Texture Is Not Showing Properly. Icon In Inventory Is Also Fine.

![Screenshot (149)](https://user-images.githubusercontent.com/98843281/162631444-7daece0c-b158-4d61-b4fc-a4f0d74aae29.png)

![Screenshot (150)](https://user-images.githubusercontent.com/98843281/162631448-4f7f984f-62c4-4c78-8a34-b6cae97599c1.png)

**Comment by zeldaking** [comment]
Yeah me too

**Comment by LuckyMist8** [comment]
Well After Reloading The Game After 2 Days It Seems To Work Just Fine Now.

I Don't Know What Could Have Caused This The First Time, But It May Just Be A One Time Thing.
