### ISSUE TITLE
No Dialogue/text for quests or with npcs

### ISSUE THREAD

**Issue by IanWi** [CEObrainz/Second-Wind#3]
Discord Name: TheAstralCat#6969

Platform: CEMU

Mod Version: 1.9.11a

Game Version: 208

Desc.: When trying to talk to any npc added by Second Wind, or trying to interact with any npc who has been given dialogue by Second Wind, their dialogue from SW does not load, and instead instantly skips all the way to the end. If it is a quest, the quest also has no dialogue, even when I look at it in my log.

Steps to reproduce: I just installed Second Wind and launched. I have tried uninstalling all other mods and second wind, then reinstalling, and that did not fix it. It simply did not give dialogue.

**Comment by CEObrainz** [comment]
Make sure your language settings in BCML are set according to the version of the game you're using (e.g EU for Europe). Once it's set hit remerge and the issue should be fixed.
