### ISSUE TITLE
Crashing when loading main menu

### ISSUE THREAD

**Issue by Kireye** [CEObrainz/Second-Wind#30]
DiscordName#: Kireye #5853

Platform: Cemu

Mod Version: v1.9.12b

Game Version: 1.5.0 (DLC 3.0 (Says 208 in Cemu))

Detailed description of the issue: While trying to load the main menu after having compiled the sharers the game crashes.  I have tried using the mod all by itself, with some workarounds installed from the Cemu 'graphics packs' menu, with and without BCML and I always get almost the same result, the only difference is that some times the emulator window will go white briefly before closing but I could not find a pattern in this behavior.

Exact steps to reproduce the issue: Instal the mod and launch the game.

EDIT 1: Ok, so, I managed to fix the problem and it was actually with modding the game in general, but I'll leave this here in case anyone else has this problem and the admins can take it down if they want.  I had to change the CPU mode in the game profile to 'Multi-core recompiler'  (it was set to 'auto' before) and that fixed the issue. No idea why... but it works so I'm not going to complain.

EDIT 2: The last edit solved the problem when using the Linkle mod, but now when using second wind, for some reason that I don't think god even knows.

EDIT C(hicken): IT'S THE CHICKENS! I went to the wiki and downloaded all the mods marked as 'Unnecessary' separately and tested them. All of them worked EXCEPT the one that changes the Cucco textures. So I'm pretty sure that it's the chickens making my life a living hell. So if anyone knows a way to get rid of the chicken mod I would greatly appreciate if you could inform me of the method.

**Comment by CEObrainz** [comment]
SW doesn't require any additional mods, it includes everything you need within the initial download. Compatibility cannot be guaranteed with additional/standalone mods.
