### ISSUE TITLE
Bird Man Mask missing name and description when upgrade

### ISSUE THREAD

**Issue by h4rl0ck48** [CEObrainz/Second-Wind#31]
DiscordName#: h4rl0ck48#1482

Platform: Cemu

Mod Version: SWNighgtly 5/26/22 (This not new issue I just forgot to report earlier)

Game Version: 1.5

Detailed description of the issue: After upgrading the Bird Man Mask, the name and description disappears. 

Exact steps to reproduce the issue: Upgrade mask on Fairy fountain 
![Screenshot from 2022-05-27 08-37-55](https://user-images.githubusercontent.com/46299750/170702003-676bf26b-5ea1-4932-932a-6448fe0a58c5.png)

**Comment by CEObrainz** [comment]
Fixed in 2022/08/05 nightly
