### ISSUE TITLE
Game stuck in animation. Mail box

### ISSUE THREAD

**Issue by h4rl0ck48** [CEObrainz/Second-Wind#35]
DiscordName#: h4rl0ck48#1482

Platform: Cemu

Mod Version: SWNightly 6/19/22

Game Version: 1.5.0

Detailed description of the issue:

The game gets stuck initiating animation before the dialogue with the mail box. There is no ctd or visual bugs, you can move the camera around Link but thats is it. Game won't move pas that point

Exact steps to reproduce the issue:

Interact with the mail box.

**Comment by CEObrainz** [comment]
Fixed in SWNightly
