### ISSUE TITLE
A pic-ture Hunt: Adept possible bug

### ISSUE THREAD

**Issue by h4rl0ck48** [CEObrainz/Second-Wind#4]
H4rl0ck71#1482
Cemu 1.25.6
SW 1.9.11a
BTOW DLC ver 3.0
The quest starts correctly. After showing the picture of the Ordon Goat, the bunny, the rat and the Owl the quest ends, if talking again the quest restart but text said to look for the Ordon Goat again on the dialog box, all tho in the quest log does says to show the picture of a Mammoth when taking the picture of the Mammoth the "!" Is shown but after taking the picture the sign disappears. Once you talk to Ture again there is no option to show the picture of the Mammoth.

**Comment by CEObrainz** [comment]
This issue is currently being fixed, waiting on an image that'll be uploaded sometime tomorrow and then I'll close this bug.

**Comment by CEObrainz** [comment]
Fixed with latest nightly release.
