### ISSUE TITLE
Can't get past the loading screen

### ISSUE THREAD

**Issue by Dremii** [CEObrainz/Second-Wind#40]
TITLE: Brief Description of the issue:

DiscordName#: Dremii#5196

Platform: Wii U

Mod Version: 1.9.12

Game Version: 1.5.0

Detailed description of the issue: I decided to run the mod on my Wii U because I wanted to an authentic Zelda experience, but when I boot up the mod itself, it crashes. The farthest into the game i've gotten is to the loading screen, but even then it doesn't show the current achievements in the top right corner such as number of hearts.

Exact steps to reproduce the issue: Boot the game on a Wii u lmao

I'm so sorry to bother, I just really would like to enjoy this mod because I've heard great things about it

**Comment by CEObrainz** [comment]
Double check the installation guide: https://github.com/Torphedo/BOTW-ModdingGuide/wiki/SW-Installation-Hub
