### ISSUE TITLE
Stuck with npc

### ISSUE THREAD

**Issue by loppanisoppan** [CEObrainz/Second-Wind#41]
Mod version: 1.9.12
Game version: 1.5.0
DLC version: 3.0

When I go to talk with the npc that lives in house north of kakariko I'm not able to press 'B' and go away.

**Comment by lntrc** [comment]
FWIW the same thing started to happen with Marin at Link's house recently (nightly, Wii U). Pressing B triggers the dialog again

**Comment by loppanisoppan** [comment]
@lntrc Are there any ways to fix it? Or should i just wait for an update with a bugfix?

**Comment by CEObrainz** [comment]
**I can't see any of the new text, what do I do?**

Make sure your language settings in BCML are set according to the version of the game you're using (e.g EU for Europe). Once it's set hit remerge and the issue should be fixed.

**Comment by lntrc** [comment]
"Make sure your language settings in BCML": this FAQ answer has absolutely nothing to do with the issue that Marin's English dialog is looping. Intentionally misleading or dev can't read.

**Comment by CEObrainz** [comment]
> 

This isn't your ticket, the response was to the person who opened the ticket.
