### ISSUE TITLE
Areas of hyrule castle unloading

### ISSUE THREAD

**Issue by kyoukyubi** [CEObrainz/Second-Wind#44]
![image](https://user-images.githubusercontent.com/111627197/186073106-4755e446-3419-43c6-a248-9555b6ebc3a6.png)
![image](https://user-images.githubusercontent.com/111627197/186073160-a870abdd-df98-445c-839e-b39dca5710c1.png)
Discord name: Kyoukyubi#1562
Platform: Cemu 1.26.2f
Mod version: 1.9.13
Game version EUv208
Description: entering various areas of Hyrule Castle causes the area to seemingly unload, despawning enemies and making navigation virtually impossible.
how to reproduce: just walk indoors in hyrule castle.

**Comment by CEObrainz** [comment]
Fixed in 1.9.13a
