### ISSUE TITLE
Hinox king statue bug

### ISSUE THREAD

**Issue by draveloxd** [CEObrainz/Second-Wind#5]
DiscordName#:  GAAAnyu#5958

Platform: Wii U/Cemu or Switch/Yuzu/Ryujinx: Cemu

Mod Version: latest

Game Version: latest

Detailed description of the issue: At first it let me enter the hinox king cave but after killing the boss I wasn't able to 
interact with the statue to come back. Now after re-installing I can't even interact with the statue to get into the cave.
![a0a5efb41f4abc981a373f62a5692ff7](https://user-images.githubusercontent.com/98126279/150422344-b6e7b484-a34b-480b-a106-b89ae5d2489b.jpg)

**Comment by ZombiePelican007** [comment]
same here you can get back in if you reload where you were and get lucky I clipped outside of the map and still couldn't find the interact button.

**Comment by h4rl0ck48** [comment]
Latest nightly update seems to fix the ability to interact with the statue outside and after u finish the quest

**Comment by draveloxd** [comment]
Sorry for ignorance, what is the nightly update?

**Comment by draveloxd** [comment]
Yes, fixed now with the latest nightly update

**Comment by CEObrainz** [comment]
Fixed in Nightly, fix will be in v1.9.12
