### ISSUE TITLE
Titles and Descriptions missing when using Zelda's Ballad.

### ISSUE THREAD

**Issue by tjohnson1284** [CEObrainz/Second-Wind#56]
Whenever I have Zelda's Ballad installed with Second Wind, the titles and descriptions of items and quests are missing. 

Installed Mods:
Zelda's Ballad v1.2(either animation set has the error)
Second Wind v1.9.13

CEMU Version: 2.0-7
BCML Version: 3.9.26

BOTW Wii U(v208), all DLC installed, latest version.
[zelda_second_wind_screenshots.zip](https://github.com/CEObrainz/Second-Wind/files/9793204/zelda_second_wind_screenshots.zip)

**Comment by CEObrainz** [comment]
Update to Second Wind v1.9.13a and downgrade Cemu to 1.26.2f
