### ISSUE TITLE
Champion's tunic bug

### ISSUE THREAD

**Issue by N9fyz** [CEObrainz/Second-Wind#7]
SW creates a bug when playing with the mod zelda's ballad, and displays the tunic of link instead of zelda's one.

DiscordName : Nn9ne

Platform : Wii U Cemu 

Mod version: 1.9.11b

Game version: Cemu 1.16.1 Game Version 208 dlc 80

Detailed description of the issue: More info on the picture

Exact steps to reproduce the issue : Install the mod zelda's ballad + second wind

![bug](https://user-images.githubusercontent.com/98340697/150826794-aef14c77-9435-481d-8f5a-b0291d8507c5.JPG)

**Comment by CEObrainz** [comment]
This looks like a mod compatibility issue. I'd suggest ensuring SW is priority 100 and then retesting.
