### ISSUE TITLE
Devoted Ruler bug

### ISSUE THREAD

**Issue by h4rl0ck48** [CEObrainz/Second-Wind#9]
On nightly version when the devoted ruler quest start and arrived to were the yiga member is, the "!" does not show up and the yiga member never gives you the chest, I fought like 12 yiga member by sleeping to the next day or night and never got the chest, this does not happens on 1.9.11a, I switched to test it and worked 1st time.

**Comment by h4rl0ck48** [comment]
Issue was solve with latest nightly version

**Comment by CEObrainz** [comment]
Fixed in Nightly, fix will be in v1.9.12
